// Generated by trace_charm_floors.py. Original AABB pads from occupancy.
// Do not import FBX.
// Filter=ED80. pads=24 extent=192x240m cell=8.0m
#pragma once

struct FCLGeneratedFloorPad
{
	float CenterX;
	float CenterY;
	float CenterZ;
	float SizeXMeters;
	float SizeYMeters;
};

static const FCLGeneratedFloorPad GSocialExtractedPads[] =
{
	{ -2000.0f, 1200.0f, 422.6f, 32.00f, 64.00f },
	{ 5200.0f, -12800.0f, 277.2f, 32.00f, 40.00f },
	{ -2400.0f, -3600.0f, 439.4f, 40.00f, 32.00f },
	{ 400.0f, -8800.0f, 397.3f, 16.00f, 56.00f },
	{ 800.0f, -800.0f, 546.0f, 8.00f, 104.00f },
	{ -1600.0f, -14000.0f, 397.3f, 24.00f, 32.00f },
	{ 0.0f, 0.0f, 545.7f, 8.00f, 88.00f },
	{ 3200.0f, -8800.0f, 333.2f, 8.00f, 72.00f },
	{ 2400.0f, -8000.0f, 172.8f, 8.00f, 72.00f },
	{ 1600.0f, -7200.0f, 312.2f, 8.00f, 72.00f },
	{ 2800.0f, -14000.0f, 397.3f, 16.00f, 32.00f },
	{ 4400.0f, -8400.0f, 334.2f, 16.00f, 32.00f },
	{ -800.0f, -8800.0f, 455.9f, 8.00f, 40.00f },
	{ 1600.0f, 0.0f, 397.3f, 8.00f, 40.00f },
	{ -1200.0f, -11600.0f, 397.3f, 16.00f, 16.00f },
	{ -4400.0f, 3600.0f, 584.6f, 16.00f, 16.00f },
	{ -6800.0f, 4000.0f, 597.3f, 32.00f, 8.00f },
	{ -3200.0f, -13600.0f, 397.6f, 8.00f, 24.00f },
	{ 0.0f, -13600.0f, 397.3f, 8.00f, 24.00f },
	{ 7200.0f, -12800.0f, 202.2f, 8.00f, 24.00f },
	{ 4800.0f, -10400.0f, 397.3f, 24.00f, 8.00f },
	{ 1600.0f, 3600.0f, 447.3f, 8.00f, 16.00f },
	{ 10400.0f, -19200.0f, 362.8f, 8.00f, 8.00f },
	{ 4000.0f, -6400.0f, 0.0f, 8.00f, 8.00f },
};

static const FVector GSocialExtractedPlayerStart(0.0f, 0.0f, 745.7f);
