@startuml occupy_flank_orbit
floating note
onRespawn: patrol_to_live_occupy
onStop: occupy_flank_orbit
trySuccessFor: 2.0
end note
start
:goto marker=live_orbit;
note right
  while: trackFocus, fire
  success: distXY 100
  goodEnough: distXY 160
  fail.timeout: 40
end note
:goto marker=live_orbit;
note right
  while: trackFocus, fire
  success: distXY 100
  goodEnough: distXY 160
  fail.timeout: 40
end note
:goto marker=live_orbit;
note right
  while: trackFocus, fire
  success: distXY 100
  goodEnough: distXY 160
  fail.timeout: 40
end note
:goto marker=live_orbit;
note right
  while: trackFocus, fire
  success: distXY 100
  goodEnough: distXY 160
  fail.timeout: 40
end note
stop
@enduml
